#!/usr/bin/bash
bg_color=black
fg_color=white
normal_color=150:150:150
font="DroidSansMono Nerd Font"
separator_left=
separator_right=

blogo() {
  # shellcheck disable=SC2001
  echo -e ':\n1:\n2:\n3:\n4:\n5:\n6:\n7:\n8:\n9:\n10:' | grep -E "^$(echo "$battery_capacity" | sed 's/.$//'):" | cut -d: -f2
}

vlogo() {
  [ $volume -eq 0 ] && echo "🔇" || echo "🔊"
}

wlogo() {
  logotable='vlc:嗢 \nmpv: \nchromium: \nfirefox: \nalacritty: \ndiscord:ﭮ \n.*: '
  IFS='';
  echo -e "$logotable" | while read -r line
do
  cmd=$(echo "$line" | cut -d: -f1)
  if echo "$windowcommand" | grep "$cmd" >/dev/null
  then
    echo "$line" | cut -d: -f2
    break
  fi
done
}

draw() {
  leftmost
  left "$(blogo)"  "$(gauge "$battery_capacity"         "%"  50 20)"
  left " "        "$(gauge "$cpu"                      "%"  40 70)"
  left ""         "$(gauge "$temp"                     "°C" 40 70)"
  left "$(wlogo)"  "${windowname}${additional_spaces}"
  rightmost
  right " "       "$date"
  right " "       "$(gauge "$mem"                      "%"  30 70)"
  right "$(vlogo)" "$(gauge "$volume"                   "%"  60 120)"
}
